Projects/P1Project/P1Shop/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ModelsLibary;
using BusinessLayer;
using System.Dynamic;

namespace P1Shop.Controllers
{

    public class CartController : Controller
    {

        private  readonly ICartLogic _cartLogic;
        private readonly IProduct _productLogic;
        private readonly IOrderLogic _orderLogic;
        private readonly IOrderDetailLogic _orderDetailLogic;
        private readonly IStoreLogic _storeLogic;




        public CartController(ICartLogic cartLogic, IProduct productLogic, IOrderDetailLogic orderDetailLogic, IOrderLogic orderLogic, IStoreLogic storeLogic)
        {
            this._cartLogic = cartLogic;
            this._productLogic = productLogic;
            this._orderDetailLogic = orderDetailLogic;
            this._orderLogic = orderLogic;
            this._storeLogic = storeLogic;
            
        }

       

        /// <summary>
        /// Method to display product Info before to buy
        /// </summary>
        /// <param name="store"></param>
        /// <returns></returns>
        public async Task<ActionResult> ProductInfoCart(ProductModel product)
        {

            var productInfo = await _productLogic.GetProductInfoAsync(product);

            CartModel item = new CartModel();

            item.ProductOne = productInfo;
           
            return View("ProductInfoCart", item);

        }






        /// <summary>
        /// Add Item to a list in CartLogic and return the store for
        /// see more items
        /// </summary>
        /// <param name="item"></param>
        /// <returns></returns>
        public async Task<ActionResult> AddProduct(CartModel item) 
        {

           StoreModel store =  await _cartLogic.AddToCartAsync(item);

          
            return RedirectToAction("ShowProductList","Product",store);
        }





        /// <summary>
        /// Show the list of items in the acrt att the moment
        /// </summary>
        /// <param name="item"></param>
        /// <returns></returns>
        public async Task<ActionResult> CartList()
        {

            List<CartModel> listCart = new List<CartModel>(await _cartLogic.ShowCartList());

            return View("CartList", listCart);
        }







        /// <summary>
        /// Method for set the order to the db
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> SetOrder()
        {
           
           await _cartLogic.AddOrderAsync();
            ///print your order
            return RedirectToAction("ShowStoreList", "Store");
        }




        public IActionResult Index()
        {
            return View();
        }
    }
}

Projects/P1Project/P1Shop/Controllers/ShopController.cs
using BusinessLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModelsLibary;
using P1Shop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace P1Shop.Controllers
{

    /// <summary>
    /// Class ShopCpntroller inhereting from Controller
    /// </summary>
    public class ShopController : Controller
    {
        private readonly IShopLogic _shopLogic;
        
        private readonly ICartLogic _cartLogic;

       

        //create a constructor into which i will inject the shoplogic Class from business layer.
        public ShopController(IShopLogic shopLogic, ICartLogic cartLogic)
        {
            this._shopLogic = shopLogic;
            
            this._cartLogic = cartLogic;
        }


        

        // GET: ShopController
        /// <summary>
        /// Actiom method Login for enter in the program and validate the user
        /// </summary>
        /// <returns></returns>
        public async Task <ActionResult> Login(CustomerModel customerLogin)
        {

           bool validation = await _shopLogic.CustomerLoginAsync(customerLogin);

            if (validation)
            {
               var cts = _cartLogic.CustomerTransfer(customerLogin);
               AccountLogic.SaveCustomer(cts);

                return View("LoggeInLandingPage",customerLogin);
            }
            else {
                return View("Login"); 
            
            }
        }





        /// <summary>
        /// Return to main
        /// </summary>
        /// <returns></returns>
        public ActionResult Main()
        {
            return View("LoggeInLandingPage", AccountLogic.GetCustomer());
        }






        // GET: ShopController/Details/5
        /// <summary>
        /// Actiom method Details the comment on top is the looks of the url
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            return View();
        }



        // GET: ShopController/Create - This is conventional routing.
        /// <summary>
        /// Action method Create the comment on top is the looks of the url
        /// This method take you to the view were you can enter the new customer info
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View("CreateNewCustomer");
        }

        


        //[Route("Create")]//for routing to a sertian page
        //This is Model Biding system take the data form &
        //matches it to the props models.
        /// <summary>
        /// This method Display the customer info before adding him to the 
        /// DB
        /// </summary>
        /// <param name="customer"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateNewCustomer(CustomerModel customer)
        {

            if (!ModelState.IsValid)
            {
                RedirectToAction("Create");
            }     

                return View("DisplayNewCustomer", customer); 
            
        }






        /// <summary>
        /// this action methos add a new customer on the db
        /// </summary>
        /// <param name="customer"></param>
        /// <returns></returns>
        public async Task<ActionResult> AddCustomer(CustomerModel customer)
        {
            //check that the model binding work
            if (!ModelState.IsValid)
            {
                RedirectToAction("Create");
            }

            //call a method in the business layer
            bool sucessfullAdded = await _shopLogic.RegisterCustomerAsync(customer);//for mockin the testing is a interface for implementing in unit testing

            if (sucessfullAdded)
            {
                ViewBag.Welcome = "You are in addCustomer action";

                return View("Login");
            }
            else
            {
                ViewBag.ErrorViewBag = "AddCustomer hava a error";
                return View("Error");
            }     
        }



        /// <summary>
        /// Display option for enter search by name or last name
        /// </summary>
        /// <param name="customerFName"></param>
        /// <returns></returns>
        public ActionResult SearchByName()
        {

            return View("SearchByName");
        }


        /// <summary>
        /// Search Customer by First Name
        /// </summary>
        /// <param name="customerName"></param>
        /// <returns></returns>
        public async Task<ActionResult> SearchForCustomer(CustomerModel customerName)
        {

            List<CustomerModel> customerSearch = await _shopLogic.CustomerSearchAsync(customerName);

            if(customerSearch == null)
            {
                RedirectToAction("LoggeInLandingPage");
            }

            return View("SearchForCustomer", customerSearch);
        }


        /// <summary>
        /// Search Customer by FirstName and Last Name
        /// </summary>
        /// <param name="customerName"></param>
        /// <returns></returns>
        public async Task<ActionResult> SearchForCustomerFL(CustomerModel customerName)
        {

            List<CustomerModel> customerSearch = await _shopLogic.CustomerSearchFLAsync(customerName);

            if (customerSearch == null)
            {
                RedirectToAction("LoggeInLandingPage");
            }

            return View("SearchForCustomer", customerSearch);
        }


        /// <summary>
        /// This method display a list of all customers
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> ShowCustomerList()
        {
            List<CustomerModel> customerList = await _shopLogic.CustomerListAsync();

            return View("ShowCustomerList",customerList);
        }

















        // POST: ShopController/Create
        [HttpPost]//anotations -->This make the action method HTTP Post method only
        [ValidateAntiForgeryToken]//anotation
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // GET: ShopController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }


        // POST: ShopController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // GET: ShopController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ShopController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Projects/P1Project/P1Shop/Views/Cart/CartList.cshtml
@model IEnumerable<ModelsLibary.CartModel>

@{
    ViewData["Title"] = "CartList";

    decimal total = 0;
}

<h1>CartList</h1>



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductOne.ProductId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductOne.Product_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductOne.Product_Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductOne.Product_Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductOne.Product_Stock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                 @item.ProductOne.ProductId
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductOne.Product_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductOne.Product_Description)
            </td>
            <td>
                $@Html.DisplayFor(modelItem => item.ProductOne.Product_Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductOne.Product_Stock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantity)
            </td>
            <td>
                    @{    
                        total += item.quantity * item.ProductOne.Product_Price;
                    }
               
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
        } 
        <p><b>Total Amount:</b>$@total</p>
        @Html.ActionLink("Main", "Main","Shop") |
        @Html.ActionLink("CheckOut","SetOrder","Cart")
    </tbody>     
</table>

Projects/P1Project/P1Shop/Views/Cart/ProductInfoCart.cshtml
@model ModelsLibary.CartModel

@{
    ViewData["Title"] = "ProductInfoCart";
}

<h1>ProductInfoCart</h1>

<h4>CartModel</h4>
<hr />

<div>
    <h4>Customer Information: (Verify your information!!)</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2" >
            @Html.DisplayNameFor(model => model.ProductOne.Product_Name)
        </dt>
        <dd class = "col-sm-10" >
            @Html.DisplayFor(model => model.ProductOne.Product_Name)
        </dd>
        <dt class = "col-sm-2" >
            @Html.DisplayNameFor(model => model.ProductOne.Product_Description)
        </dt>
        <dd class = "col-sm-10" >
            @Html.DisplayFor(model => model.ProductOne.Product_Description)
        </dd>
        <dt class = "col-sm-2" >
            @Html.DisplayNameFor(model => model.ProductOne.Product_Price)
        </dt>
        <dd class = "col-sm-10" >
            @Html.DisplayFor(model => model.ProductOne.Product_Price)
        </dd>
        <dt class = "col-sm-2" >
            @Html.DisplayNameFor(model => model.ProductOne.Product_Stock)
        </dt>
        <dd class = "col-sm-10" >
            @Html.DisplayFor(model => model.ProductOne.Product_Stock)
        </dd>
       
    </dl>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddProduct">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <input type="hidden" asp-for="ProductOne.ProductId" class="form-control" readonly="@(true)"/>
                <input type="hidden" asp-for="ProductOne.Product_Name" class="form-control" readonly="@(true)"/>
                <input type="hidden" asp-for="ProductOne.Product_Description" class="form-control" readonly="@(true)"/>
                <input type="hidden" asp-for="ProductOne.Product_Price" class="form-control" readonly="@(true)"/>
                <input type="hidden" asp-for="ProductOne.Product_Stock" class="form-control" readonly="@(true)"/>
                <input type="hidden" asp-for="ProductOne.LocationId" class="form-control" readonly="@(true)"/>

                <label asp-for="quantity" class="control-label"><b>Quantity:</b></label>
                <input asp-for="quantity" class="form-control" min="0" max="100"/>
                <span asp-validation-for="quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="BuyNow!" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
   
</div>