Projects/P1Project/P1Shop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer;
using ModelsLibary;

namespace P1Shop.Controllers
{
    public class OrderController : Controller
    {
        
        private readonly IOrderLogic _orderLogic;
        private readonly IOrderDetailLogic _orderDetailLogic;

        public OrderController(IOrderLogic orderLogic, IOrderDetailLogic orderDetailLogic)
        {

            this._orderLogic = orderLogic;
            this._orderDetailLogic = orderDetailLogic;
           

        }


        /// <summary>
        /// Display orders belong to that specific customer
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> ShowCustomerOrders()
        {
            
            var customer = AccountLogic.GetCustomer();

            List<OrderModel> orders = null;

             orders = await _orderLogic.AllOrders(customer);


            return View("ShowCustomerOrders", orders);
        }
















        // GET: OderController
        public ActionResult Index()
        {
            return View();
        }

        // GET: OderController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: OderController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OderController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: OderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OderController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Projects/P1Project/P1Shop/Controllers/ShopController.cs
using BusinessLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModelsLibary;
using P1Shop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace P1Shop.Controllers
{

    /// <summary>
    /// Class ShopCpntroller inhereting from Controller
    /// </summary>
    public class ShopController : Controller
    {
        private readonly IShopLogic _shopLogic;
        
        private readonly ICartLogic _cartLogic;

       

        //create a constructor into which i will inject the shoplogic Class from business layer.
        public ShopController(IShopLogic shopLogic, ICartLogic cartLogic)
        {
            this._shopLogic = shopLogic;
            
            this._cartLogic = cartLogic;
        }


        

        // GET: ShopController
        /// <summary>
        /// Actiom method Login for enter in the program and validate the user
        /// </summary>
        /// <returns></returns>
        public async Task <ActionResult> Login(CustomerModel customerLogin)
        {

           bool validation = await _shopLogic.CustomerLoginAsync(customerLogin);

            if (validation)
            {
               var cts = _cartLogic.CustomerTransfer(customerLogin);
               AccountLogic.SaveCustomer(cts);

                return View("LoggeInLandingPage",customerLogin);
            }
            else {
                return View("Login"); 
            
            }
        }





        /// <summary>
        /// Return to main
        /// </summary>
        /// <returns></returns>
        public ActionResult Main()
        {
            return View("LoggeInLandingPage", AccountLogic.GetCustomer());
        }






        // GET: ShopController/Details/5
        /// <summary>
        /// Actiom method Details the comment on top is the looks of the url
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            return View();
        }



        // GET: ShopController/Create - This is conventional routing.
        /// <summary>
        /// Action method Create the comment on top is the looks of the url
        /// This method take you to the view were you can enter the new customer info
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View("CreateNewCustomer");
        }

        


        //[Route("Create")]//for routing to a sertian page
        //This is Model Biding system take the data form &
        //matches it to the props models.
        /// <summary>
        /// This method Display the customer info before adding him to the 
        /// DB
        /// </summary>
        /// <param name="customer"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateNewCustomer(CustomerModel customer)
        {

            if (!ModelState.IsValid)
            {
                RedirectToAction("Create");
            }     

                return View("DisplayNewCustomer", customer); 
            
        }






        /// <summary>
        /// this action methos add a new customer on the db
        /// </summary>
        /// <param name="customer"></param>
        /// <returns></returns>
        public async Task<ActionResult> AddCustomer(CustomerModel customer)
        {
            //check that the model binding work
            if (!ModelState.IsValid)
            {
                RedirectToAction("Create");
            }

            //call a method in the business layer
            bool sucessfullAdded = await _shopLogic.RegisterCustomerAsync(customer);//for mockin the testing is a interface for implementing in unit testing

            if (sucessfullAdded)
            {
                ViewBag.Welcome = "You are in addCustomer action";

                return View("Login");
            }
            else
            {
                ViewBag.ErrorViewBag = "AddCustomer hava a error";
                return View("Error");
            }     
        }



        /// <summary>
        /// Display option for enter search by name or last name
        /// </summary>
        /// <param name="customerFName"></param>
        /// <returns></returns>
        public ActionResult SearchByName()
        {

            return View("SearchByName");
        }


        /// <summary>
        /// Search Customer by First Name
        /// </summary>
        /// <param name="customerName"></param>
        /// <returns></returns>
        public async Task<ActionResult> SearchForCustomer(CustomerModel customerName)
        {

            List<CustomerModel> customerSearch = await _shopLogic.CustomerSearchAsync(customerName);

            if(customerSearch == null)
            {
                RedirectToAction("LoggeInLandingPage");
            }

            return View("SearchForCustomer", customerSearch);
        }


        /// <summary>
        /// Search Customer by FirstName and Last Name
        /// </summary>
        /// <param name="customerName"></param>
        /// <returns></returns>
        public async Task<ActionResult> SearchForCustomerFL(CustomerModel customerName)
        {

            List<CustomerModel> customerSearch = await _shopLogic.CustomerSearchFLAsync(customerName);

            if (customerSearch == null)
            {
                RedirectToAction("LoggeInLandingPage");
            }

            return View("SearchForCustomer", customerSearch);
        }


        /// <summary>
        /// This method display a list of all customers
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> ShowCustomerList()
        {
            List<CustomerModel> customerList = await _shopLogic.CustomerListAsync();

            return View("ShowCustomerList",customerList);
        }

















        // POST: ShopController/Create
        [HttpPost]//anotations -->This make the action method HTTP Post method only
        [ValidateAntiForgeryToken]//anotation
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // GET: ShopController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }


        // POST: ShopController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // GET: ShopController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ShopController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Projects/P1Project/P1Shop/Controllers/StoreController.cs
using BusinessLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModelsLibary;
using P1Shop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace P1Shop.Controllers
{
    public class StoreController : Controller
    {


        private readonly IStoreLogic _storeLogic;
        

        //create a constructor into which i will inject the shoplogic Class from business layer.
        public StoreController(IStoreLogic shopLogic)
        {
            this._storeLogic = shopLogic;     
        }


        /// <summary>
        /// Display the all the store in the Db
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> ShowStoreList()
        {
            List<StoreModel> storeList = await _storeLogic.StoreListAsync();

            return View("ShowStoreList", storeList);
        }



        /// <summary>
        /// Method to display Store Info
        /// </summary>
        /// <param name="store"></param>
        /// <returns></returns>
        public async Task<ActionResult> StoreInfo(StoreModel store)

        {
            var storeInfo = await _storeLogic.GetStoreInfoAsync(store);

            return View("StoreInfo", storeInfo);

        }





        // GET: StoreController
        public ActionResult Index()
        {
            return View();
        }

        // GET: StoreController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: StoreController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StoreController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StoreController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: StoreController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StoreController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: StoreController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Projects/P1Project/P1Shop/Views/Shop/CreateNewCustomer.cshtml
<!--this is the model stringly types to this view --> 
@model ModelsLibary.CustomerModel

@{
    ViewData["Title"] = "CreateNewCustomer";
}

<h1>Create New Customer</h1>

<h4>Just Register in Seconds</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateNewCustomer"><!--This denote the action that the form will be sent to-->
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>


            <div class="form-group">
                <label asp-for="Customer_FName" class="control-label" ></label>
                <input asp-for="Customer_FName" class="form-control />
                <span asp-validation-for="Customer_FName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer_LName" class="control-label"></label>
                <input asp-for="Customer_LName" class="form-control" />
                <span asp-validation-for="Customer_LName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer_Address" class="control-label"></label>
                <input asp-for="Customer_Address" class="form-control" />
                <span asp-validation-for="Customer_Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer_City" class="control-label"></label>
                <input asp-for="Customer_City" class="form-control" />
                <span asp-validation-for="Customer_City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Customer_State" class="control-label"></label>
                <input asp-for="Customer_State" class="form-control" />
                <span asp-validation-for="Customer_State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back","Index","Home")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projects/P1Project/P1Shop/Views/Shop/DisplayNewCustomer.cshtml
@model ModelsLibary.CustomerModel

@{
    ViewData["Title"] = "DisplayNewCustomer";
}

<h1>New Customer Informatio</h1>

<div>
    <h4>Customer Information: (Verify your information!!)</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2" hidden>
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd class = "col-sm-10" hidden>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer_FName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer_FName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer_LName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer_LName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer_Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer_Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer_City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer_City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer_State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer_State)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Submit New Customer", "AddCustomer", @Model) |
     @Html.ActionLink("Back", "Index","Home") 
</div>

Projects/P1Project/P1Shop/Views/Shop/LoggeInLandingPage.cshtml
@{

    ViewData["Title"] = "Store Dashboard";
}

 <h1>@ViewData["Title"]</h1>

<h3> @ViewData["Welcome"]@Model.Customer_FName Account:</h3>


<container>
    <div>
              <button class="btn-info"><a class="btn" asp-area="" asp-controller="Shop" asp-action="ShowCustomerList">Show Customer List</a></button>
              <button class="btn-info"><a class="btn" asp-area="" asp-controller="Shop" asp-action="SearchByName">Search Customer</a></button>
              <button class="btn-info"><a class="btn" asp-area="" asp-controller="Store" asp-action="ShowStoreList">Stores List</a></button>
              <button class="btn-info"><a class="btn" asp-area="" asp-controller="Order" asp-action="ShowCustomerOrders">Show Orders</a></button>
               
    </div>
</container>

Projects/P1Project/P1Shop/Views/Shop/Login.cshtml
@model ModelsLibary.CustomerModel

@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Customer_FName" class="control-label"></label>
                <input asp-for="Customer_FName" class="form-control" />
                
            </div>
            
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                
            </div>
            
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
            
        </form>
            
    </div>
</div>

<div>
    @Html.ActionLink("Back", "Index","Home")
</div>

Projects/P1Project/P1Shop/Views/Shop/SearchByName.cshtml
@model ModelsLibary.CustomerModel

@{
    ViewData["Title"] = "SearchByName";
}

<h1>Search By First Name</h1>


<hr />
<div class="row">
    <div class="col-md-4">

        <form asp-action="SearchForCustomer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Customer_FName" class="control-label"></label>
                <input asp-for="Customer_FName" class="form-control" />
                <span asp-validation-for="Customer_FName" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>

    </div>
</div>

<h1>Search By First and Last Name</h1>
<div class="row">
    <div class="col-md-4">

        <form asp-action="SearchForCustomerFL">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Customer_FName" class="control-label"></label>
                <input asp-for="Customer_FName" class="form-control" />
                <span asp-validation-for="Customer_FName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Customer_LName" class="control-label"></label>
                <input asp-for="Customer_LName" class="form-control" />
                <span asp-validation-for="Customer_FName" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>

    </div>
</div>

<div>
    
    @Html.ActionLink("Main Menu","Main","Shop")

</div>

Projects/P1Project/P1Shop/Views/Shop/SearchForCustomer.cshtml
@model IEnumerable<ModelsLibary.CustomerModel>

@{
    ViewData["Title"] = "SearchForCustomer";
}

<h1>SearchForCustomer</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer_FName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer_LName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer_Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer_City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer_State)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_FName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_LName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_State)
            </td>
            <td>
               
                
            </td>
        </tr>
}
    </tbody>
</table>
@Html.ActionLink("Back", "SearchByName","Shop")

Projects/P1Project/P1Shop/Views/Shop/ShowCustomerList.cshtml
@model IEnumerable<ModelsLibary.CustomerModel>

@{
    ViewData["Title"] = "ShowCustomerList";
}

<h1>Customer List</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer_FName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer_LName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer_Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer_City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer_State)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_FName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_LName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer_State)
            </td>
            
        </tr>
}
    </tbody>
</table>

@Html.ActionLink("Main Menu","Main","Shop")